ccc/core/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'pas.views.home'),
    url(r'^pas/', include('pas.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
)

ccc/pas/urls.py
# -*- coding: UTF-8 -*-

#         app: Control de planes de acción y seguimiento
#      modulo: pas.urls
# descripcion: Redirecciones para sgc-pas
#       autor: Javier Sanchez Toledano
#       fecha: miércoles, 1 de octubre de 2014

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'pas.views',
    url(r'^$', 'pas_home', name='pas'),
    url(r'^plan/(?P<id>\d+)$', 'plan', name='pas_plan'),
    url(r'^add/$', 'add', name='pas_add'),
    url(r'seguimiento/(?P<id>\d+)$', 'seguimiento', name='seguimiento')
)

ccc/pas/models.py
# -*- coding: UTF-8 -*-

#         app: Control de Planes de Acción
#      modulo: pas.models
# descripcion: Modelos para Control de Planes de Acción
#       autor: Javier Sanchez Toledano
#       fecha: jueves, 2 de octubre de 2014


from django.db import models
from tinymce.models import HTMLField
import datetime
# import magic
from django.utils.translation import ugettext as _


class Pipol (models.Model):
    class Meta:
        verbose_name = _('Pipol')
        verbose_name_plural = _('Personas')

    nombre = models.CharField(max_length=60)

    def __unicode__(self):
        return '%s' % self.nombre


class TrackingFields(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

PROCESO = (
    (1, 'Planeación'),
    (2, 'Apoyo Soporte'),
    (3, 'Clave'),
    (4, 'MSA'),
    (5, 'SGC'),
)

TIPO = (
    (1, 'Reactivo'),
    (2, 'Incremental'),
    (3, 'Innovación'),
    (4, 'Avance'),
    (5, 'Transformación'),
)

DETECCION = (
    (1, 'Auditoria Interna'),
    (2, 'Auditoria Externa'),
    (3, 'Revisión por los Vocales'),
    (4, 'Quejas'),
    (5, 'Otros'),
)

MEJORA = (
    (1, 'Procesos'),
    (2, 'Servicio'),
    (3, 'Sistema')
)

A_ESTADO = (
    (1, u'Seguimiento'),
    (2, u'Revisión de Evidencia'),
    (3, u'En espera de una respuesta'),
    (4, u'En espera de una acción'),
    (5, u'En espera de un evento'),
    (6, u'Cerrada')
)

JPG = 'image/jpeg'
PDF = 'application/pdf'
PNG = 'image/png'


class Plan(models.Model):
    class Meta:
        verbose_name = _(u'Plan de Acción')
        verbose_name_plural = _(u'Planes de Acción')
    # #################################### #
    # I. Identificación del plan
    fecha_llenado = models.DateField(
        'Fecha de Llenado',
        default=datetime.date.today()
    )
    fecha_deteccion = models.DateField('Fecha de Detección')
    proceso = models.PositiveSmallIntegerField(choices=PROCESO)
    tipo = models.PositiveSmallIntegerField(choices=TIPO)
    deteccion = models.PositiveSmallIntegerField(choices=DETECCION)
    mejora = models.PositiveSmallIntegerField(choices=MEJORA)
    nombre = models.CharField(max_length=40)

    # #################################### #
    # II. Revisión
    redaccion = HTMLField(default='', blank=True, null=True)
    declaracion = HTMLField(default='', blank=True, null=True)
    evidencia = HTMLField(default='', blank=True, null=True)
    requisitos = HTMLField(default='', blank=True, null=True)
    relacionadas = HTMLField(default='', blank=True, null=True)

    # #################################### #
    # III. Responsabilidades
    informacion = models.CharField(max_length=30, blank=True, null=True)
    aplicacion = models.CharField(max_length=30, blank=True, null=True)
    responsable = models.CharField(max_length=30, blank=True, null=True)

    # #################################### #
    # IV. Reacción
    correccion = HTMLField(default="", blank=True, null=True)
    consecuencias = models.FileField(upload_to='pas', blank=True, null=True)
    reaccion_responsable = models.ForeignKey(
        Pipol, blank=True, null=True)
    reaccion_evidencia = models.FileField(upload_to='pas', blank=True, null=True)

    # #################################### #
    # V. Determinación de las Causas
    pescadito = models.FileField(upload_to='pas', blank=True, null=True)
    cincopq = models.FileField('5 Por qués', upload_to='pas', blank=True, null=True)
    causa_raiz = HTMLField(default='', blank=True, null=True)

    # #################################### #
    # VI. Implementación de Acciones

    # #################################### #
    # VII. Revisión de la eficacia de las acciones

    # #################################### #
    # VIII. Cierre
    eliminacion = models.BooleanField(default=False)
    txt_eliminacion = HTMLField(blank=True, null=True)
    recurrencia = models.BooleanField(default=False)
    txt_recuerrencia = HTMLField(blank=True, null=True)

    def __unicode__(self):
        return u'%s' % self.nombre


class Accion(models.Model):
    class Meta:
        verbose_name = _(u'Acción Correctiva')
        verbose_name_plural = _('Acciones Correctivas')
    plan = models.ForeignKey(Plan)
    accion = HTMLField()
    recursos = HTMLField(blank=True, null=True)
    fecha = models.DateField()
    responsable = models.ForeignKey(Pipol)

    def _get_estado(self):
        "Regresa el estado de una acción correctiva, de acuerdo al último seguimiento capturado"
        if self.seguimiento_set.count() == 0:
            if self.fecha >= datetime.date.today():
                return 'Abierta en Tiempo'
            else:
                return 'Abierta Fuera de Tiempo'
        else:
            return self.seguimiento_set.latest().get_estado_display()
    estado = property(_get_estado)

    def __unicode__(self):
        return u'%s - %s: %s' % (self.id, self.plan, self.estado)


class Seguimiento(TrackingFields, models.Model):
    class Meta:
        verbose_name = _(u'Seguimiento de Acciones')
        verbose_name_plural = _('Seguimiento')
        get_latest_by = 'fecha'
        get_latest_by = 'modified'
    accion = models.ForeignKey(Accion)
    descripcion = HTMLField()
    fecha = models.DateField()
    evidencia = models.FileField(upload_to='pas', blank=True, null=True)
    estado = models.PositiveSmallIntegerField(choices=A_ESTADO)
    responsable = models.ForeignKey(Pipol)

    def __unicode__(self):
        return u'%s - %s: %s' % (self.accion, self.fecha, self.get_estado_display())

ccc/pas/forms.py
# -*- coding: UTF-8 -*-

#         app: Control de Planes de Acción
#      modulo: pas.forms
# descripcion: Formularios
#       autor: Javier Sanchez Toledano
#       fecha: viernes, 3 de octubre de 2014

from .models import Plan
from .models import PROCESO, TIPO, DETECCION, MEJORA
from django import forms
from tinymce.widgets import TinyMCE


class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        exclude = []

    fecha_deteccion = forms.DateField(
        input_formats=['%d/%m/%Y', ],
        widget=forms.TextInput(
            attrs={'class': 'form-control', }
        )
    )
    proceso = forms.CharField(
        widget=forms.widgets.Select(
            choices=PROCESO,
            attrs={'class': 'form-control', }
        )
    )
    tipo = forms.CharField(
        widget=forms.widgets.Select(
            choices=TIPO,
            attrs={'class': 'form-control', }
        )
    )
    deteccion = forms.CharField(
        widget=forms.widgets.Select(
            choices=DETECCION,
            attrs={'class': 'form-control', }
        )
    )
    mejora = forms.CharField(
        widget=forms.widgets.Select(
            choices=MEJORA,
            attrs={'class': 'form-control', }
        )
    )

    redaccion = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )
    declaracion = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )
    evidencia = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )
    correccion = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )
    causa_raiz = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )
    relacionadas = forms.CharField(
        widget=TinyMCE(attrs={'cols': 50, 'rows': 3, 'class': 'form-control'})
    )

ccc/pas/views.py
# -*- coding: UTF-8 -*-

#         app: Planes de Acción y Seguimiento
#      modulo: ccc.pas.views
# descripcion: Vistas para manejar los planes de acción
#       autor: Javier Sanchez Toledano
#       fecha: miércoles, 1 de octubre de 2014


from .models import Plan, Accion
from .forms import PlanForm
from annoying.decorators import render_to
from django.http import HttpResponseRedirect


@render_to('index_pas.html')
def home(request):
    planes = Plan.objects.all()
    titulo = u'Control de Planes de Acción y Seguimiento'
    return {
        'planes': planes,
        'title': titulo
    }


@render_to('plan.html')
def plan(request, id):
    plan = Plan.objects.get(pk=id)
    titulo = u'%s | Plan de Acción y Seguimiento' % plan.nombre
    return {
        'title': titulo,
        'plan': plan
    }


@render_to('add.html')
def add(request, pas_id=None):
    if pas_id:
        pas = Plan.objects.get(pk=pas_id)
    else:
        pas = Plan()
    if request.method == 'POST':
        form = PlanForm(request.POST, instance=pas)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            ruta = '/pas/'
            return HttpResponseRedirect(ruta)

    else:
        form = PlanForm(instance=pas)

    return {
        'title': 'Agregar nuevo PAS',
        'form': form
    }

@render_to('seguimiento.html')
def seguimiento(request, id):
    accion = Accion.objects.get(pk=id)
    return {
        'title': 'Lista de actividades de seguimiento',
        'accion': accion
    }

ccc/pas/templates/add.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
<link href="{% static 'pas/css/datepicker3.css' %}" rel="stylesheet">
{% endblock header %}

{% block post_footer %}
<script src="{% static 'pas/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'pas/js/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
  $('#fecha_deteccion_widget input').datepicker({
    format: "dd/mm/yyyy",
    weekStart: 1,
    todayBtn: true,
    language: "es",
    forceParse: false,
    daysOfWeekDisabled: "0,6",
    autoclose: true,
    todayHighlight: true
  });
</script>
{{ form.media }}
{% endblock post_footer %}

{% block contenido %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1><i class="fa fa-bug"></i> Agregar un nuevo plan <small>Mejora</small></h1>
    </div>
  </div>
</div>

<div class="row">
  <form class="form-horizontal" role="form">
    {% csrf_token %}
    <div class="row"><!-- Identificacion -->
      <div class="col-md-8">
        <div id="identificacion" class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-bullhorn"></i> Identificación del Plan</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label for="id_fecha_deteccion" class="col-md-4 control-label">Fecha de Detección</label>
              <div class="col-md-4 date" id="fecha_deteccion_widget">
                {{ form.fecha_deteccion }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_proceso" class="col-md-4 control-label">Proceso</label>
              <div class="col-md-4">
                {{ form.proceso }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_tipo" class="col-md-4 control-label">Tipo de Plan</label>
              <div class="col-md-4">
                {{ form.tipo }}
              </div>
              <div class="col-md-2">
                <span class="label label-danger">2015</span>
              </div>
            </div>
            <div class="form-group">
              <label for="id_deteccion" class="col-md-4 control-label">Detectada durante:</label>
              <div class="col-md-4">
                {{ form.deteccion }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_mejora" class="col-md-4 control-label">Mejora de:</label>
              <div class="col-md-4">
                {{ form.mejora }}
              </div>
              <div class="col-md-1">
                <span class="label label-danger">9001:2015</span>
              </div>
            </div> 
          </div>                
        </div><!-- ./#identificacion -->
      </div>
      <div class="col-md-4">
        <div class="well">
          <h4>10.1 Generalidades</h4>
          <p>
            La organización debe determinar y seleccionar las oportunidades de mejora e implementar las acciones necesarias para cumplir los requisitos del cliente y aumentar la satisfacción del cliente.
          </p>
          <p>
            Esto debe incluir, cuando sea adecuado;
            <ol type="a">
              <li>mejorar los procesos para prevenir no conformidades;</li>
              <li>mejorar los productos y servicios para cumplir los requisitos conocidos y previstos;</li>
              <li>mejorar los resultados del sistema de gestión de la calidad.</li>
            </ol>
          </p>
        </div>
      </div>
    </div><!-- ./Identificacion -->
    <div class="row"><!-- Reacción -->
      <div class="col-md-8">
        <div id="reaccion" class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fire-extinguisher"></i> Reacción <small><span class="label label-danger">v 2015</span></small></h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label for="id_correccion" class="col-md-4 control-label">Correción</label>
              <div class="col-md-7">
                {{ form.correccion }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_consecuencias" class="col-md-4 control-label">Consecuencias</label>
              <div class="col-md-7">
                <div class="form-control-wrapper fileinput">
                  {{ form.consecuencias }}
                </div>
              </div>
            </div>
          </div>
        </div><!-- ./reaccion -->
      </div>
      <div class="col-md-4">
        <div class="well">
          <p>
          <strong>10.2.1</strong> Cuando ocurra una no conformidad, incluidas aquellas originadas por quejas, la organización debe:</p>
          <ol start="1">
            <li>
              reaccionar ante la no conformidad, y según sea aplicable
              <ol type="a">
                <li>tomar acciones para controlarla y corregirla;</li>
                <li>hacer frente a las consecuencias;</li>
              </ol>
            </li>
          </ol>  
        </div>
      </div>
    </div><!-- ./Reaccion -->
    <div class="row"><!-- Revision -->
      <div class="col-md-8">
        <div id="declaracion" class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-briefcase"></i> Revisión</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label for="id_redaccion" class="col-md-4 control-label">Redacción</label>
              <div class="col-md-7">
                {{ form.redaccion }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_declaracion" class="col-md-4 control-label">Declaración</label>
              <div class="col-md-7">
                {{ form.declaracion }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_evidencia" class="col-md-4 control-label">Evidencia</label>
              <div class="col-md-7">
                {{ form.evidencia }}
              </div>
            </div>
          </div>
        </div><!-- ./#declaracion -->
      </div>
      <div class="col-md-4">
        <div class="well">
          <ol start="2">
            <li>
              evaluar la necesidad de acciones para eliminar las causas de la no conformidad, con el fin de que no vuelva a ocurrir ni ocurra en otra parte, mediante:
              <ol type="a">
                <li>la revisión de la no conformidad;</li>
              </ol>
            </li>
          </ol>
        </div>
      </div>
    </div><!-- ./Revision -->
    <div class="row"><!-- Causas -->
      <div class="col-md-8">
        <div class="panel panel-info" id="causas">
          <div class="panel-heading">
            <h3 class="panel-title">
              <i class="fa fa-paw"></i> Determinación de las causas
            </h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label for="id_pescadito" class="col-md-4 control-label">Diagrama de Pescado</label>
              <div class="col-md-7">
                {{ form.pescadito }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_cincopq" class="col-md-4 control-label">Cinco Por Qué's</label>
              <div class="col-md-7">
                {{ form.cincopq }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_causa_raiz" class="col-md-4 control-label">Causa Raíz</label>
              <div class="col-md-7">
                {{ form.causa_raiz }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_relacionadas" class="col-md-4 control-label">No conformidades relacionadas</label>
              <div class="col-md-7">
                {{ form.relacionadas }}
              </div>
            </div>
          </div>
        </div><!-- ./#causas -->
      </div>
      <div class="col-md-4">
        <div class="well">
          <ol start="2">
            <li>
              <p>...</p>
              <ol type="a" start="2">
                <li>la determinación de las causas de la no conformidad;</li>
                <li>la determinación de si existen no conformidades similares, o que potencialmente podrían ocurrir;</li>
              </ol>
            </li>
          </ol>
        </div>
      </div>
    </div><!-- ./Causas -->
  </form>
</div>

{% endblock contenido %}

ccc/pas/templates/index.html
{% extends 'base.html' %}

{% block pre_contenido %}
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h1>
          <i class="icon icon-material-bug-report"></i> 
          Control de Planes de Acción
        </h1>
        <p>
          La organización debe determinar y seleccionar las oportunidades de mejora e implementar las acciones necesarias para cumplir los requisitos del cliente y aumentar la satisfacción del cliente.
        </p>
        <p>
          <a href="javascript:void(0)" class="btn btn-danger">Seguimiento</a>
          <a href="javascript:void(0)" class="btn btn-success">Acción Compromiso</a>
          <a href="javascript:void(0)" class="btn btn-info">Agregar un PAS</a>
        </p>
      </div>
    </div>
  </div>
{% endblock pre_contenido %}

{% block contenido %}
<div class="row">
  {% for p in planes %}
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><a href="{% url 'pas_plan' p.id %}">{{ p.nombre }}</a></h4>
        </div>
        <div class="panel-body">
          {{ p.redaccion|safe }}
        </div>
        <div class="panel-footer">
          Accciones: <span class="badge">{{ p.accion_set.count }}</span> | 
          <span class="label label-primary">{{ p.get_proceso_display }}</span> |
          <span class="label label-success">{{ p.get_tipo_display }}</span> |
          <span class="label label-info">{{ p.get_mejora_display }}</span>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock contenido %}

ccc/pas/templates/plan.html
{% extends 'base.html' %}

{% block post_footer %}
<script type="text/javascript">
  function abrir(pagina) {
    var strWindowFeatures = "menubar=no,resizable=no,scrollbars=yes,status=no,width=600,height=400";
    window.open(pagina, 'window', strWindowFeatures).focus();
  }

  $('#myModal').on('hide.bs.modal', function(e) {
      $(this).removeData('bs.modal');
  });
</script>
{% endblock post_footer %}

{% block pre_contenido %}
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <h1>
        <i class="fa fa-bug"></i>
        {{ plan.nombre }} <small><span class="label label-primary">{{ plan.get_tipo_display }}</span></small>
      </h1>
      {{ plan.redaccion|safe }}
    </div>
  </div>

  <div class="col-md-12">
    <nav class="navbar navbar-default" role="navigation" id="control-pas">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#control-pas-menu">
            <span class="sr-only">Menú</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Proceso</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="control-pas-menu">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#identificacion">identificación</a></li>
            <li><a href="#decl">declaración</a></li>
            <li><a href="#corr">corrección</a></li>
            <li><a href="#causa">causa</a></li>
            <li><a href="#acciones">acciones</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>

</div>
{% endblock pre_contenido %}

{% block contenido %}

<div class="expediente" data-spy="scroll" data-target="#control-pas" data-offset="0">
  <div class="row" id="identificacion">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-info-circle"></i> Identificación</h3>
        </div>
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>Nombre: <strong>{{ plan.nombre }}</strong></td>
              <td>Detectado en: <strong>{{ plan.get_deteccion_display }}</strong></td>
              <td>Tipo: <strong>{{ plan.get_tipo_display }}</strong></td>
              <td>Mejora de: <strong>{{ plan.get_mejora_display }}</strong></td>
            </tr>
            <tr>
              <td>Folio: <strong>{{ plan.id }}</strong></td>
              <td>Proceso: <strong>{{ plan.get_proceso_display }}</strong></td>
              <td>Fecha de Llenado: <strong>{{ plan.fecha_llenado }}</strong></td>
              <td>Fecha de Detección: <strong>{{ plan.fecha_deteccion }}</strong></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row" id="decl">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-legal"></i> Declaración</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <div class="thumbnail">
                <div class="caption">
                  <h3>Redacción</h3>
                  {{ plan.redaccion|safe }}
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="thumbnail">
                <div class="caption">
                  <h3>Declaración</h3>
                  {{ plan.declaracion|safe }}
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <div class="thumbnail">
                <div class="caption">
                  <h3>Evidencias</h3>
                  {{ plan.evidencia|safe }}
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="thumbnail">
                <div class="caption">
                  <h3>Requisitos al que hace referencia</h3>
                  {{ plan.requisitos|safe }}
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="thumbnail">
                <div class="caption">
                  <h3>No conformidades o NCP relacionadas</h3>
                  {{ plan.relacionadas|safe }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- ./declaracion -->
  <div class="row" id="corr">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-fire-extinguisher"></i> Corrección</h3>
        </div>
        <div class="panel-body">
          {{ plan.correccion|safe }}
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-4">
              Responsable: <strong>{{ plan.reaccion_responsable }}</strong>
            </div>
            <div class="col-md-4">
              {% if plan.reaccion_evidencia %}Evidencia: <a target="_blank" href="{{ plan.reaccion_evidencia.url }}" onClick="abrir(this.href);return false" class="btn btn-primary btn-xs">Revisar</a>{% endif %}
            </div>
            <div class="col-md-4">
              Consecuencias: <strong>{{ plan.consecuencias }}</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- ./correccion -->
  <div class="row" id="causa">
    <div class="col-md-12">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-paw"></i> Determinación de la causa</h3>
        </div>
        <div class="panel-body">
                  <div class="row">
            <div class="col-md-6">
              <div class="thumbnail">
                <div class="caption">
                  <h3>Diagrama de Causa Raíz</h3>
                  <p>Una descripción del pescadito</p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="thumbnail">
                <div class="caption">
                  <h3>5 Por Qué's</h3>
                  <p>Técnica socrática</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <h4>Causa Raíz</h4>
          {{ plan.causa_raiz|safe }}
        </div>
      </div>
    </div>
  </div>
  <div class="row" id="acciones">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-ambulance"></i> Acciones Correctivas</h3>
        </div>
        <div class="panel-body">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="col-md-5">Acción</th>
                <th class="col-md-1">Fecha</th>
                <th class="col-md-2">Responsable</th>
                <th class="col-md-1">Seguimiento</th>
                <th class="col-md-2">Estado</th>
              </tr>
            </thead>
            <tbody>
              {% for a in plan.accion_set.all %}
                <tr>
                  <td>{{ a.accion|safe }}</td>
                  <td>{{ a.fecha|date:"d/b/Y" }}</td>
                  <td>{{ a.responsable }}</td>
                  <td>
                    <a type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal" href="{%  url 'seguimiento' id=a.id %}">
                      {{ a.seguimiento_set.count }}
                    </a>
                  </td>
                  <td>{{ a.estado }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="panel-footer">Panel footer</div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% endblock contenido %}